services:
    nginx:
        build:
            context: .
            target: nginx
        ports:
            - "80:80"
        depends_on:
            - laravel
        networks:
            - app-network

    laravel:
        build:
            context: .
            target: laravel
        networks:
            - app-network

    flask:
        build:
            context: .
            target: flask
        ports:
            - "5000:5000"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
